// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectE.Games.Data;

#nullable disable

namespace ProjectE.Games.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Games")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectE.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Games", "Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96539e50-84fa-411e-bfb0-601584a1dab5"),
                            Emoji = "🃏",
                            Name = "Slay the Spire",
                            Rating = 2019.0
                        },
                        new
                        {
                            Id = new Guid("4653eefd-5ca8-416f-95fc-81c5444d196f"),
                            Emoji = "🃏",
                            Name = "Inscryption",
                            Rating = 2021.0
                        },
                        new
                        {
                            Id = new Guid("2762c66d-ddec-439a-8107-23b4b1d0135b"),
                            Emoji = "🃏",
                            Name = "Balatro",
                            Rating = 2024.0
                        },
                        new
                        {
                            Id = new Guid("41009adf-7f4f-47a6-8878-4dd7b797fdd0"),
                            Emoji = "👻",
                            Name = "Lethal Company",
                            Rating = 2023.0
                        },
                        new
                        {
                            Id = new Guid("ed380097-59a6-4988-ac90-6971656d9d6b"),
                            Emoji = "👻",
                            Name = "Content Warning",
                            Rating = 2024.0
                        },
                        new
                        {
                            Id = new Guid("40cd4519-0088-40ad-8802-5bd48277ed27"),
                            Emoji = "👻",
                            Name = "Phasmophobia",
                            Rating = 2020.0
                        },
                        new
                        {
                            Id = new Guid("f50109a8-e896-4057-8ead-32fbdc6bb308"),
                            Emoji = "🌄",
                            Name = "Terraria",
                            Rating = 2011.0
                        },
                        new
                        {
                            Id = new Guid("cb7e4820-eb31-4a15-8493-f2cedae0c152"),
                            Emoji = "🌄",
                            Name = "Stardew Valley",
                            Rating = 2016.0
                        },
                        new
                        {
                            Id = new Guid("55c16bbe-d6c5-4c6f-b892-7bac72b26e71"),
                            Emoji = "🌄",
                            Name = "Undertale",
                            Rating = 2015.0
                        },
                        new
                        {
                            Id = new Guid("e80c6d13-abfe-4928-9f40-0eae0c4c6b38"),
                            Emoji = "🐸",
                            Name = "Hades",
                            Rating = 2020.0
                        },
                        new
                        {
                            Id = new Guid("5ffd015b-4045-412a-82cc-e46665fc6ec5"),
                            Emoji = "🐸",
                            Name = "Risk of Rain 2",
                            Rating = 2020.0
                        },
                        new
                        {
                            Id = new Guid("d88c04ca-e535-428f-9182-f63a92934d97"),
                            Emoji = "🐸",
                            Name = "Dead Cells",
                            Rating = 2018.0
                        },
                        new
                        {
                            Id = new Guid("6e074183-70a5-486e-b6a7-950108d493c2"),
                            Emoji = "💟",
                            Name = "Portal 2",
                            Rating = 2011.0
                        },
                        new
                        {
                            Id = new Guid("9e615e17-0e24-4881-8454-b12bd172cae8"),
                            Emoji = "💟",
                            Name = "We Were Here Together",
                            Rating = 2019.0
                        },
                        new
                        {
                            Id = new Guid("f97c8c66-9dfb-4ebd-902d-93710d6605f5"),
                            Emoji = "💟",
                            Name = "Haven",
                            Rating = 2020.0
                        },
                        new
                        {
                            Id = new Guid("34fcf3ec-d35e-4d02-906c-64ed86555929"),
                            Emoji = "🥲",
                            Name = "Elden Ring",
                            Rating = 2022.0
                        },
                        new
                        {
                            Id = new Guid("edbf998c-5a48-45b1-bc43-1b810d98269d"),
                            Emoji = "🥲",
                            Name = "Bloodborne",
                            Rating = 2015.0
                        },
                        new
                        {
                            Id = new Guid("a6132bec-de8c-4df6-bb47-e72d053ae040"),
                            Emoji = "🥲",
                            Name = "Sekiro: Shadows Die Twice",
                            Rating = 2019.0
                        },
                        new
                        {
                            Id = new Guid("1b8d5904-6a34-4793-ba18-7c5471e11c8e"),
                            Emoji = "🌦️",
                            Name = "Spiritfarer",
                            Rating = 2020.0
                        },
                        new
                        {
                            Id = new Guid("d9aad535-1e2f-4908-8090-18dcc5ff0a06"),
                            Emoji = "🌦️",
                            Name = "Stray",
                            Rating = 2022.0
                        },
                        new
                        {
                            Id = new Guid("6ad0a3da-1f70-4e8e-b5b4-6f05ed8fac7a"),
                            Emoji = "🌦️",
                            Name = "Wandersong",
                            Rating = 2018.0
                        },
                        new
                        {
                            Id = new Guid("6c43c854-eef9-417e-8703-23e68f6c9f6a"),
                            Emoji = "🫶",
                            Name = "Celeste",
                            Rating = 2018.0
                        },
                        new
                        {
                            Id = new Guid("887eae4c-280a-486c-b96a-c8fe21a3ca63"),
                            Emoji = "🫶",
                            Name = "Hollow Knight",
                            Rating = 2017.0
                        },
                        new
                        {
                            Id = new Guid("f931325e-c134-45bb-84aa-9e3118c0d055"),
                            Emoji = "🫶",
                            Name = "Jump King",
                            Rating = 2019.0
                        },
                        new
                        {
                            Id = new Guid("755b409d-1e15-4eb2-a3ea-dddfcb718e4e"),
                            Emoji = "💀",
                            Name = "Ultrakill",
                            Rating = 2020.0
                        },
                        new
                        {
                            Id = new Guid("6592b6e7-d9ff-4ed1-ad52-581c58785a6d"),
                            Emoji = "💀",
                            Name = "Dusk",
                            Rating = 2018.0
                        },
                        new
                        {
                            Id = new Guid("4a758435-c5f7-4c22-8758-6047e994b7e9"),
                            Emoji = "💀",
                            Name = "BPM: BULLETS PER MINUTE",
                            Rating = 2020.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
