// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectE.Music.Data;

#nullable disable

namespace ProjectE.Music.Data.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20240425110633_Data")]
    partial class Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Music")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectE.Music.Music", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Music", "Music");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9268891c-3aa8-4aff-ac5a-4454fa6aa672"),
                            Artist = "Human League",
                            Emoji = "⚡️💭",
                            SongName = "Electric Dreams"
                        },
                        new
                        {
                            Id = new Guid("f25c986b-fc36-439e-bc29-9616ff2d7e95"),
                            Artist = "Queen",
                            Emoji = "👑🎶",
                            SongName = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = new Guid("850111d5-6409-4196-a362-c53f007ed4dd"),
                            Artist = "Sting",
                            Emoji = "💔♠️",
                            SongName = "Shape of My Heart"
                        },
                        new
                        {
                            Id = new Guid("59fdc46f-8528-44c3-8095-ebbc6e5785ea"),
                            Artist = "Avicii",
                            Emoji = "📶",
                            SongName = "Levels"
                        },
                        new
                        {
                            Id = new Guid("444521eb-fc20-4cf5-b935-fd6008b928bf"),
                            Artist = "Avicii",
                            Emoji = "💉",
                            SongName = "Addicted To You"
                        },
                        new
                        {
                            Id = new Guid("8e488507-57e1-4709-b31f-d05c2d1795df"),
                            Artist = "Cyndi Lauper",
                            Emoji = "👩‍👧‍👧🎉",
                            SongName = "Girls Just Want to Have Fun"
                        },
                        new
                        {
                            Id = new Guid("9d07a75b-3dd0-4a86-8142-761f5621ef3c"),
                            Artist = "a-ha",
                            Emoji = "👨‍🎨📺",
                            SongName = "Take On Me"
                        },
                        new
                        {
                            Id = new Guid("54c24bd3-3eae-40a2-b6cb-8404171b8e55"),
                            Artist = "Whitney Houston",
                            Emoji = "💃👩‍❤️‍👨",
                            SongName = "I Wanna Dance with Somebody"
                        },
                        new
                        {
                            Id = new Guid("f5eddd4b-31b7-40da-8625-6bc1c05d478b"),
                            Artist = "Survivor",
                            Emoji = "👁️🐅",
                            SongName = "Eye of the Tiger"
                        },
                        new
                        {
                            Id = new Guid("36924e37-aa68-4918-927b-48b57b8b5d7d"),
                            Artist = "Journey",
                            Emoji = "🛣️🎤",
                            SongName = "Don't Stop Believin'"
                        },
                        new
                        {
                            Id = new Guid("c9b5b5b3-cf48-4096-8c3f-3d49e8372089"),
                            Artist = "Toto",
                            Emoji = "🌍🦓",
                            SongName = "Africa"
                        },
                        new
                        {
                            Id = new Guid("74487c32-e158-4eb7-9ad8-77c88b2fd308"),
                            Artist = "Neil Diamond",
                            Emoji = "🍭💎",
                            SongName = "Sweet Caroline"
                        },
                        new
                        {
                            Id = new Guid("8c1e9e28-ae50-4437-ba25-d1b6e542e306"),
                            Artist = "Dexys Midnight Runners",
                            Emoji = "🤵👱‍♀️",
                            SongName = "Come On Eileen"
                        },
                        new
                        {
                            Id = new Guid("e8a3a187-11d3-42d2-b2e7-cf743da2f1dc"),
                            Artist = "Ricky Martin",
                            Emoji = "🎉🌎",
                            SongName = "Livin' La Vida Loca"
                        },
                        new
                        {
                            Id = new Guid("64ed785a-b6da-43d4-981e-2290fbb6a72d"),
                            Artist = "Kenny Loggins",
                            Emoji = "👞💃",
                            SongName = "Footloose"
                        },
                        new
                        {
                            Id = new Guid("0e4bc0a4-3e7a-4a7b-b98d-02402139e4ad"),
                            Artist = "George Michael",
                            Emoji = "💔🎷",
                            SongName = "Careless Whisper"
                        },
                        new
                        {
                            Id = new Guid("2bdf4c4f-196b-462e-b857-c3bc85d55e6f"),
                            Artist = "Bonnie Tyler",
                            Emoji = "🌑💔",
                            SongName = "Total Eclipse of the Heart"
                        },
                        new
                        {
                            Id = new Guid("46e914e2-5c60-44a3-97a5-f2df13aaed89"),
                            Artist = "Michael Jackson",
                            Emoji = "🥁👊",
                            SongName = "Beat It"
                        },
                        new
                        {
                            Id = new Guid("a36db7b0-20de-4e9d-a482-df7ba1395f3c"),
                            Artist = "Michael Jackson",
                            Emoji = "👨🔍🪞",
                            SongName = "Man in the Mirror"
                        },
                        new
                        {
                            Id = new Guid("98fd4f42-b4a1-4644-9344-25a343f3c89b"),
                            Artist = "Pink Floyd",
                            Emoji = "🧱🧱🧱",
                            SongName = "Another Brick in the Wall"
                        },
                        new
                        {
                            Id = new Guid("3ff00557-4e4e-4b11-82a1-92fbd6d188e3"),
                            Artist = "John Travolta & Olivia Newton-John",
                            Emoji = "👫💖",
                            SongName = "You're the One That I Want"
                        },
                        new
                        {
                            Id = new Guid("2d6d2865-0ec2-47d4-abe1-cc8bf2444652"),
                            Artist = "Poison",
                            Emoji = "🌹🎸💔",
                            SongName = "Every Rose Has Its Thorn"
                        },
                        new
                        {
                            Id = new Guid("bb37ec6a-3f78-4d92-83f0-1a02ba253512"),
                            Artist = "Joan Jett & the Blackhearts",
                            Emoji = "🎸🖤",
                            SongName = "I Love Rock 'n' Roll"
                        },
                        new
                        {
                            Id = new Guid("54553a19-7599-4655-bf43-141b3e40574d"),
                            Artist = "AC/DC",
                            Emoji = "🛣️😈",
                            SongName = "Highway to Hell"
                        },
                        new
                        {
                            Id = new Guid("2d537b70-306d-4678-81f3-1d8a28c25438"),
                            Artist = "Queen",
                            Emoji = "🏆👑",
                            SongName = "We Are the Champions"
                        },
                        new
                        {
                            Id = new Guid("30e8be19-cabb-4fc2-ae33-f74a84eeb441"),
                            Artist = "Queen",
                            Emoji = "👑🎸",
                            SongName = "We Will Rock You"
                        },
                        new
                        {
                            Id = new Guid("272bd92b-7f2d-49eb-9a94-7a9c3ff870c4"),
                            Artist = "Queen",
                            Emoji = "💀🎶",
                            SongName = "Another One Bites the Dust"
                        },
                        new
                        {
                            Id = new Guid("199b3034-5b8b-4648-b7f4-89fc2fa537f0"),
                            Artist = "Queen",
                            Emoji = "🆓🎶",
                            SongName = "I Want to Break Free"
                        },
                        new
                        {
                            Id = new Guid("f6d80f06-ec46-49f8-9275-d59c8a68ac30"),
                            Artist = "Queen & David Bowie",
                            Emoji = "🎶🔨❄️",
                            SongName = "Under Pressure"
                        },
                        new
                        {
                            Id = new Guid("c1e3f73d-2b26-48b1-a3d7-9f1b415cd8d5"),
                            Artist = "Queen",
                            Emoji = "🎵❤️",
                            SongName = "Somebody to Love"
                        },
                        new
                        {
                            Id = new Guid("8c5cf2e8-4c9c-453b-9dfb-b2e75a5f59ad"),
                            Artist = "Queen",
                            Emoji = "📻👑",
                            SongName = "Radio Ga Ga"
                        },
                        new
                        {
                            Id = new Guid("7e7937c6-8747-4a0f-81b4-3c464f6e88e2"),
                            Artist = "Queen",
                            Emoji = "👑🎶",
                            SongName = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = new Guid("05931f03-ec5e-4b68-8e1c-fc2bbfe27f47"),
                            Artist = "Queen",
                            Emoji = "👑👸",
                            SongName = "Killer Queen"
                        },
                        new
                        {
                            Id = new Guid("0f22a7f2-5a12-4b1d-9365-4d63581a63e9"),
                            Artist = "Queen",
                            Emoji = "💖🎶",
                            SongName = "Love of My Life"
                        },
                        new
                        {
                            Id = new Guid("fa87c373-e0b5-46c6-a277-c35734fb5394"),
                            Artist = "Queen",
                            Emoji = "🛑🚀",
                            SongName = "Don't Stop Me Now"
                        },
                        new
                        {
                            Id = new Guid("b9a491e2-11e9-4b3c-bb8e-0c88be87d0de"),
                            Artist = "Queen",
                            Emoji = "🍑👩",
                            SongName = "Fat Bottomed Girls"
                        },
                        new
                        {
                            Id = new Guid("c09e84d8-7da4-4c36-bf90-84008e019de1"),
                            Artist = "USA for Africa",
                            Emoji = "🌎👫🎵",
                            SongName = "We Are the World"
                        },
                        new
                        {
                            Id = new Guid("9b23d302-88b5-4749-aa7d-c54ee9bc79b9"),
                            Artist = "Michael Jackson",
                            Emoji = "🌍👨‍👩‍👦‍👦",
                            SongName = "Heal the World"
                        },
                        new
                        {
                            Id = new Guid("b8f8b5e0-2481-4a38-8715-c9b98c63c760"),
                            Artist = "Michael Sembello",
                            Emoji = "🏃‍♂️💃",
                            SongName = "Maniac"
                        },
                        new
                        {
                            Id = new Guid("7ed19a5b-8c2c-4048-b2f5-c1a0e6d98c3c"),
                            Artist = "Michael Jackson",
                            Emoji = "🧟🌃",
                            SongName = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("4efc7e89-74e1-4ae1-b22a-fdbb027c1ab0"),
                            Artist = "Michael Jackson",
                            Emoji = "🕴🔫",
                            SongName = "Smooth Criminal"
                        },
                        new
                        {
                            Id = new Guid("1e98208e-85c7-4b3e-8567-e1ff5e2f5d67"),
                            Artist = "Michael Jackson",
                            Emoji = "🕺🌟",
                            SongName = "Billie Jean"
                        },
                        new
                        {
                            Id = new Guid("9f944c34-dde5-41d0-9f14-1fcd9ed52d9a"),
                            Artist = "Michael Jackson",
                            Emoji = "🥁👊",
                            SongName = "Beat It"
                        },
                        new
                        {
                            Id = new Guid("b01608b3-7782-4924-97fc-d4f2f38aafab"),
                            Artist = "Michael Jackson",
                            Emoji = "👀💕",
                            SongName = "The Way You Make Me Feel"
                        },
                        new
                        {
                            Id = new Guid("6f000b7e-d79a-4c48-926b-44f361fb4d8f"),
                            Artist = "Michael Jackson",
                            Emoji = "⚫⚪",
                            SongName = "Black or White"
                        },
                        new
                        {
                            Id = new Guid("2c6d6935-0f4f-4c4b-b22e-4436aa06dbb0"),
                            Artist = "Michael Jackson",
                            Emoji = "🚫👎",
                            SongName = "Bad"
                        },
                        new
                        {
                            Id = new Guid("120b547d-9d4f-44f2-8127-e298c05e4f56"),
                            Artist = "Berlin",
                            Emoji = "🌬️💔",
                            SongName = "Take My Breath Away"
                        },
                        new
                        {
                            Id = new Guid("e21c33e8-e127-4c28-8f76-11c129fb6769"),
                            Artist = "George Michael",
                            Emoji = "💔🎷",
                            SongName = "Careless Whisper"
                        },
                        new
                        {
                            Id = new Guid("19f003d5-3fe6-4a80-8a60-90b5cd1d8e1a"),
                            Artist = "The Police",
                            Emoji = "👀👣",
                            SongName = "Every Breath You Take"
                        },
                        new
                        {
                            Id = new Guid("88b5c58a-37b7-4cf8-b92e-9d11cdd1d1a3"),
                            Artist = "Cyndi Lauper",
                            Emoji = "⏰🔄",
                            SongName = "Time After Time"
                        },
                        new
                        {
                            Id = new Guid("c8f281fa-fd8a-458d-b60d-d7e44b196df5"),
                            Artist = "Celine Dion",
                            Emoji = "💔🚢",
                            SongName = "My Heart Will Go On"
                        },
                        new
                        {
                            Id = new Guid("29220b79-1209-4fc9-9e89-c2565df2c390"),
                            Artist = "The Beatles",
                            Emoji = "📅🎵",
                            SongName = "Yesterday"
                        },
                        new
                        {
                            Id = new Guid("bd091c18-175b-4af7-926e-468c3766cf64"),
                            Artist = "Lionel Richie",
                            Emoji = "👋🎵",
                            SongName = "Hello"
                        },
                        new
                        {
                            Id = new Guid("b27b9c41-d7f8-4af6-b6f3-dc59ba25ee1a"),
                            Artist = "Whitney Houston",
                            Emoji = "💔🎶",
                            SongName = "I Will Always Love You"
                        },
                        new
                        {
                            Id = new Guid("f01f20db-c66e-464f-a54d-8f7242f92b05"),
                            Artist = "Guns N' Roses",
                            Emoji = "🍂🌧️",
                            SongName = "November Rain"
                        },
                        new
                        {
                            Id = new Guid("cef03b8b-7f24-4a95-bf4f-d78d9c4c5180"),
                            Artist = "Poison",
                            Emoji = "🌹🎸💔",
                            SongName = "Every Rose Has Its Thorn"
                        },
                        new
                        {
                            Id = new Guid("4f08b1bc-8aef-42e5-9175-0626ab69f162"),
                            Artist = "Joan Jett & the Blackhearts",
                            Emoji = "🎸🖤",
                            SongName = "I Love Rock 'n' Roll"
                        },
                        new
                        {
                            Id = new Guid("6e01b8a2-c228-42aa-8da5-8281db2dc589"),
                            Artist = "Bon Jovi",
                            Emoji = "🙏🎸",
                            SongName = "Livin' on a Prayer"
                        },
                        new
                        {
                            Id = new Guid("12058a5a-89f5-45f4-94fb-d5bb16b44a82"),
                            Artist = "Guns N' Roses",
                            Emoji = "🍬👶🎸",
                            SongName = "Sweet Child o' Mine"
                        },
                        new
                        {
                            Id = new Guid("a7d02de7-7c28-4cd1-a1d2-0a53c3c60d89"),
                            Artist = "AC/DC",
                            Emoji = "🛣️😈",
                            SongName = "Highway to Hell"
                        },
                        new
                        {
                            Id = new Guid("d6c7f7e2-f4c8-4e70-bd9e-47ac218f0132"),
                            Artist = "Queen",
                            Emoji = "🏆👑",
                            SongName = "We Are the Champions"
                        },
                        new
                        {
                            Id = new Guid("22a24321-7e5e-48d6-80bb-b8888bcbce2e"),
                            Artist = "Queen",
                            Emoji = "👑🎸",
                            SongName = "We Will Rock You"
                        },
                        new
                        {
                            Id = new Guid("c6ccfd21-f085-4641-b570-22d261e48926"),
                            Artist = "Queen",
                            Emoji = "💀🎶",
                            SongName = "Another One Bites the Dust"
                        },
                        new
                        {
                            Id = new Guid("b8dd307f-4f15-4996-9e8a-f03d2d59bc96"),
                            Artist = "Queen",
                            Emoji = "🆓🎶",
                            SongName = "I Want to Break Free"
                        },
                        new
                        {
                            Id = new Guid("71e745f5-35b0-4fe4-a0cc-97a0d73654cc"),
                            Artist = "Queen & David Bowie",
                            Emoji = "🎶🔨❄️",
                            SongName = "Under Pressure"
                        },
                        new
                        {
                            Id = new Guid("92d20026-b92f-4317-b3b2-0e6153288b7c"),
                            Artist = "Queen",
                            Emoji = "🎵❤️",
                            SongName = "Somebody to Love"
                        },
                        new
                        {
                            Id = new Guid("15b4c9fb-83cd-4a06-9b5a-1cc9e66a5a89"),
                            Artist = "Queen",
                            Emoji = "📻👑",
                            SongName = "Radio Ga Ga"
                        },
                        new
                        {
                            Id = new Guid("d8e1a7dc-8722-4374-9941-622c344b0f60"),
                            Artist = "Queen",
                            Emoji = "👑🎶",
                            SongName = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = new Guid("b78d13d7-78f2-4e0b-b95b-69ff9df44419"),
                            Artist = "Queen",
                            Emoji = "👑👸",
                            SongName = "Killer Queen"
                        },
                        new
                        {
                            Id = new Guid("0f3f1275-cf79-4a65-aaf7-7e4d991cc4e0"),
                            Artist = "Queen",
                            Emoji = "💖🎶",
                            SongName = "Love of My Life"
                        },
                        new
                        {
                            Id = new Guid("8a63da2e-6fa6-42ec-bc58-40937976c123"),
                            Artist = "Queen",
                            Emoji = "🛑🚀",
                            SongName = "Don't Stop Me Now"
                        },
                        new
                        {
                            Id = new Guid("5cb1d6d7-3b02-4d72-a9e0-67abcc16d191"),
                            Artist = "Queen",
                            Emoji = "🍑👩",
                            SongName = "Fat Bottomed Girls"
                        },
                        new
                        {
                            Id = new Guid("196839e8-0733-4813-b3e4-9edfb9917d3f"),
                            Artist = "USA for Africa",
                            Emoji = "🌎👫🎵",
                            SongName = "We Are the World"
                        },
                        new
                        {
                            Id = new Guid("ff6793b4-41a0-4629-a152-1a37d3bc1ad7"),
                            Artist = "Michael Jackson",
                            Emoji = "🌍👨‍👩‍👦‍👦",
                            SongName = "Heal the World"
                        },
                        new
                        {
                            Id = new Guid("9950b88c-ea1a-4b68-ae6d-156e86ab3842"),
                            Artist = "Michael Sembello",
                            Emoji = "🏃‍♂️💃",
                            SongName = "Maniac"
                        },
                        new
                        {
                            Id = new Guid("8e0c4ad5-1c39-4181-b2a5-d7cc80d17349"),
                            Artist = "Michael Jackson",
                            Emoji = "🧟🌃",
                            SongName = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("43f2ef8c-24b6-43f0-a94c-55c8d828079a"),
                            Artist = "Michael Jackson",
                            Emoji = "🕴🔫",
                            SongName = "Smooth Criminal"
                        },
                        new
                        {
                            Id = new Guid("4b41c417-1922-4763-98ec-b2f9e1b3b00c"),
                            Artist = "Michael Jackson",
                            Emoji = "🕺🌟",
                            SongName = "Billie Jean"
                        },
                        new
                        {
                            Id = new Guid("1f398abc-72e5-4b47-895f-4aef46e53dc3"),
                            Artist = "Michael Jackson",
                            Emoji = "🥁👊",
                            SongName = "Beat It"
                        },
                        new
                        {
                            Id = new Guid("d7a6712c-3c70-49df-8a10-3f0917c3f5fd"),
                            Artist = "Michael Jackson",
                            Emoji = "👀💕",
                            SongName = "The Way You Make Me Feel"
                        },
                        new
                        {
                            Id = new Guid("77d7d19e-d6cc-4aeb-882f-0b35e2db05ab"),
                            Artist = "Michael Jackson",
                            Emoji = "⚫⚪",
                            SongName = "Black or White"
                        },
                        new
                        {
                            Id = new Guid("73da92b1-1c0e-4a4b-8910-0529c9c5f833"),
                            Artist = "Michael Jackson",
                            Emoji = "🚫👎",
                            SongName = "Bad"
                        },
                        new
                        {
                            Id = new Guid("51e0cfd4-f93e-46a4-8576-bf1a3e64db25"),
                            Artist = "Berlin",
                            Emoji = "🌬️💔",
                            SongName = "Take My Breath Away"
                        },
                        new
                        {
                            Id = new Guid("a5b0fd3d-868e-4e19-88a5-d94448d6236c"),
                            Artist = "George Michael",
                            Emoji = "💔🎷",
                            SongName = "Careless Whisper"
                        },
                        new
                        {
                            Id = new Guid("5f7f79fd-87f5-4c3e-8f5b-7c8995122034"),
                            Artist = "The Police",
                            Emoji = "👀👣",
                            SongName = "Every Breath You Take"
                        },
                        new
                        {
                            Id = new Guid("0507276e-39b0-4d33-97fd-cb14d8bdaa2f"),
                            Artist = "Cyndi Lauper",
                            Emoji = "⏰🔄",
                            SongName = "Time After Time"
                        },
                        new
                        {
                            Id = new Guid("b31db1c8-3c39-42e9-a2d3-57f3c7e4ebe5"),
                            Artist = "Celine Dion",
                            Emoji = "💔🚢",
                            SongName = "My Heart Will Go On"
                        },
                        new
                        {
                            Id = new Guid("1da53585-99c4-48e3-b9cc-9f44748178e1"),
                            Artist = "The Beatles",
                            Emoji = "📅🎵",
                            SongName = "Yesterday"
                        },
                        new
                        {
                            Id = new Guid("8e7d0802-7861-4f3f-ba7c-8449e2f4bf29"),
                            Artist = "Lionel Richie",
                            Emoji = "👋🎵",
                            SongName = "Hello"
                        },
                        new
                        {
                            Id = new Guid("1f9ebd8b-65a7-4b40-b663-4fdcf6fd5df7"),
                            Artist = "Whitney Houston",
                            Emoji = "💔🎶",
                            SongName = "I Will Always Love You"
                        },
                        new
                        {
                            Id = new Guid("87b52bfb-f077-44fb-8257-70b195f62be8"),
                            Artist = "Guns N' Roses",
                            Emoji = "🍂🌧️",
                            SongName = "November Rain"
                        },
                        new
                        {
                            Id = new Guid("b2b92b2a-6825-4a90-8f0f-5d0a5e3f171b"),
                            Artist = "Sade",
                            Emoji = "👨‍💼🎷",
                            SongName = "Smooth Operator"
                        },
                        new
                        {
                            Id = new Guid("c52b9626-f2e4-4051-b7f0-d88c8c5b2e39"),
                            Artist = "U2",
                            Emoji = "❤️🤝",
                            SongName = "With or Without You"
                        },
                        new
                        {
                            Id = new Guid("57d7f041-991e-4a85-8b38-b2de4b6e4720"),
                            Artist = "Guns N' Roses",
                            Emoji = "🍬👶🎸",
                            SongName = "Sweet Child o' Mine"
                        },
                        new
                        {
                            Id = new Guid("5127b23e-5702-40ee-918a-fd85ee7a7d78"),
                            Artist = "Sinéad O'Connor",
                            Emoji = "🔍💔",
                            SongName = "Nothing Compares 2 U"
                        },
                        new
                        {
                            Id = new Guid("5cfb42cb-83a5-4cf0-80eb-0559a77b6c5a"),
                            Artist = "The Bangles",
                            Emoji = "🔥💖",
                            SongName = "Eternal Flame"
                        },
                        new
                        {
                            Id = new Guid("9f628037-1c4f-4b0b-a7a3-2a8eae6cf26e"),
                            Artist = "The Beatles",
                            Emoji = "🤝👐",
                            SongName = "I Want to Hold Your Hand"
                        },
                        new
                        {
                            Id = new Guid("8b73c99d-d425-44e2-a27e-99592b451947"),
                            Artist = "Prince",
                            Emoji = "💜🌧️",
                            SongName = "Purple Rain"
                        },
                        new
                        {
                            Id = new Guid("080ef095-34b1-405b-a537-789fb9d067a9"),
                            Artist = "The Police",
                            Emoji = "✨🔮",
                            SongName = "Every Little Thing She Does Is Magic"
                        },
                        new
                        {
                            Id = new Guid("4f06580e-eef5-41ac-b316-3ef54f3e203b"),
                            Artist = "Phil Collins",
                            Emoji = "🏝️🙏",
                            SongName = "Another Day in Paradise"
                        },
                        new
                        {
                            Id = new Guid("2cb56062-8994-4c38-9717-24b8c96c855e"),
                            Artist = "Foreigner",
                            Emoji = "❤️🌏",
                            SongName = "I Want to Know What Love Is"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
