// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectE.Music.Data;

#nullable disable

namespace ProjectE.Music.Data.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    partial class MusicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Music")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectE.Music.Music", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Music", "Music");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6543f18f-2166-4211-bbd0-0d757076b6f5"),
                            Artist = "Love",
                            Emoji = "🩷",
                            SongName = "Lana Del Rey"
                        },
                        new
                        {
                            Id = new Guid("e851180a-cd8e-4442-a5b1-3fd38e35c495"),
                            Artist = "Light Shower",
                            Emoji = "🩷",
                            SongName = "Melanie Martinez"
                        },
                        new
                        {
                            Id = new Guid("f3a72592-5dc8-4999-bd3b-91c6b99a88dd"),
                            Artist = "Training Season",
                            Emoji = "🩷",
                            SongName = "Dua Lipa"
                        },
                        new
                        {
                            Id = new Guid("cd0f784a-06a1-442c-921f-87cbeb5a0d93"),
                            Artist = "Without Me",
                            Emoji = "💧",
                            SongName = "Halsey"
                        },
                        new
                        {
                            Id = new Guid("1b6be275-943a-454b-b054-4eb1153af7af"),
                            Artist = "& Cry!",
                            Emoji = "💧",
                            SongName = "Middle Part "
                        },
                        new
                        {
                            Id = new Guid("c43d0481-f20b-4c48-b039-3cbc89a0574b"),
                            Artist = "Everything is Embarrassing",
                            Emoji = "💧",
                            SongName = "Sky Ferreira"
                        },
                        new
                        {
                            Id = new Guid("f1aabc42-59f6-4a64-9f16-145bd924d42c"),
                            Artist = "Fall Apart",
                            Emoji = "🥀",
                            SongName = "Post Malone"
                        },
                        new
                        {
                            Id = new Guid("405429b5-cfde-406f-82fe-fcfa5ceebf5c"),
                            Artist = "Call it Off",
                            Emoji = "🥀",
                            SongName = "Tegan and Sara & CHVRCHES"
                        },
                        new
                        {
                            Id = new Guid("a1894ad3-02f4-4516-9013-7eae0d6764e1"),
                            Artist = "Hit Me Where It Hurst",
                            Emoji = "🥀",
                            SongName = "Caroline Polachek"
                        },
                        new
                        {
                            Id = new Guid("c19d4f43-fc42-4be3-936c-df2aaafbc014"),
                            Artist = "EASY",
                            Emoji = "🍧",
                            SongName = "LE SSERAFIM"
                        },
                        new
                        {
                            Id = new Guid("f4662dbe-9666-4727-9074-727075841bc5"),
                            Artist = "MEGAVERSE",
                            Emoji = "🍧",
                            SongName = "Stray Kids"
                        },
                        new
                        {
                            Id = new Guid("e280f79b-284d-4512-9d25-2b4e8ea9d387"),
                            Artist = "SHEESH",
                            Emoji = "🍧",
                            SongName = "BABYMONSTER"
                        },
                        new
                        {
                            Id = new Guid("60d0a53f-2482-4536-b2bf-fb59b1b540da"),
                            Artist = "Lost Chapter",
                            Emoji = "⛓️",
                            SongName = "Pentakill"
                        },
                        new
                        {
                            Id = new Guid("ab1799c7-ca34-49d6-8fd1-a87a6443160e"),
                            Artist = "Hysteria",
                            Emoji = "⛓️",
                            SongName = "Muse"
                        },
                        new
                        {
                            Id = new Guid("202d7276-0bc9-4210-a912-342ca836821f"),
                            Artist = "You Give Love A Bad Name",
                            Emoji = "⛓️",
                            SongName = "Bon Jovi"
                        },
                        new
                        {
                            Id = new Guid("78eee64e-4456-4b14-b512-603c1a061219"),
                            Artist = "Material Girl",
                            Emoji = "👑",
                            SongName = "Madonna"
                        },
                        new
                        {
                            Id = new Guid("aa892533-6f75-4443-a047-3b6d4d0dea5e"),
                            Artist = "Radio Gaga",
                            Emoji = "👑",
                            SongName = "Queen"
                        },
                        new
                        {
                            Id = new Guid("07b6d031-a79a-44ce-a52d-307873c66ce7"),
                            Artist = "Smooth Criminal",
                            Emoji = "👑",
                            SongName = "Michael Jackson"
                        },
                        new
                        {
                            Id = new Guid("f016aff2-862a-416b-b46f-c5ec40ec1a80"),
                            Artist = "Don't Stop the Music",
                            Emoji = "🪩",
                            SongName = "Rihanna"
                        },
                        new
                        {
                            Id = new Guid("b6da79ad-e133-45f1-bb3b-8adc44353e26"),
                            Artist = "Gimme More",
                            Emoji = "🪩",
                            SongName = "Britney"
                        },
                        new
                        {
                            Id = new Guid("340dab64-34d3-46d0-8b4b-e48df7cbffde"),
                            Artist = "Just Dance",
                            Emoji = "🪩",
                            SongName = "Lady Gaga"
                        },
                        new
                        {
                            Id = new Guid("369cbee7-6c8a-4f25-a35b-556debfb1aea"),
                            Artist = "HUMBLE.",
                            Emoji = "🥶",
                            SongName = "Kendrick Lamar"
                        },
                        new
                        {
                            Id = new Guid("237fdd5d-41bd-425b-8678-c5facb2cad28"),
                            Artist = "Creepin",
                            Emoji = "🥶",
                            SongName = "Metro Boomin & The Weeknd & 21 Savage"
                        },
                        new
                        {
                            Id = new Guid("dc5762e6-8a34-4ae7-abe9-168625059797"),
                            Artist = "Cobra (Rock Remix)",
                            Emoji = "🥶",
                            SongName = "Megan Thee Stallion & Spiritbox"
                        },
                        new
                        {
                            Id = new Guid("1cd0e7c8-5368-4fd7-bfbc-3de2cfd27b4f"),
                            Artist = "Mary On A Cross",
                            Emoji = "💥",
                            SongName = "Ghost"
                        },
                        new
                        {
                            Id = new Guid("eb6a3906-fffc-475f-92ce-d4d28f5171ba"),
                            Artist = "Gone",
                            Emoji = "💥",
                            SongName = "Night Club & MJ Keenan"
                        },
                        new
                        {
                            Id = new Guid("0d8c9a04-09c9-4998-b91c-49f4aa510247"),
                            Artist = "Just Pretend",
                            Emoji = "💥",
                            SongName = "Bad Omens"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
