// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectE.Movies.Data;

#nullable disable

namespace ProjectE.Movies.Data.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20240521202005_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Movies")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectE.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("float(3)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Movies", "Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc7354e3-d210-4d78-ad78-aea1cf750878"),
                            Emoji = "🛰️",
                            Rating = 8.0,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = new Guid("cec6ea94-91b2-4fb8-adaa-d79dbf7993e0"),
                            Emoji = "🛰️",
                            Rating = 8.6999999999999993,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = new Guid("1fb473de-4e19-454a-9e71-9333b7ce1c88"),
                            Emoji = "🛰️",
                            Rating = 8.0,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = new Guid("849e8fbf-186a-4684-94ef-749c9cb97657"),
                            Emoji = "🧝‍♀️",
                            Rating = 8.9000000000000004,
                            Title = "The Fellowship of the Ring "
                        },
                        new
                        {
                            Id = new Guid("b372fb74-26ee-41f7-9557-e00c95422609"),
                            Emoji = "🧝‍♀️",
                            Rating = 7.7999999999999998,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("cb0d79d9-506e-4dfb-8805-2cddc447f819"),
                            Emoji = "🧝‍♀️",
                            Rating = 6.9000000000000004,
                            Title = "The Chronicles of Narnia"
                        },
                        new
                        {
                            Id = new Guid("dff682eb-87b6-40ee-96fb-4fe819e3a3f7"),
                            Emoji = "🎤 ",
                            Rating = 8.5,
                            Title = "Whiplash"
                        },
                        new
                        {
                            Id = new Guid("414d085f-528c-45fe-8749-ee2e13bbe20a"),
                            Emoji = "🎤 ",
                            Rating = 8.0,
                            Title = "La La Land"
                        },
                        new
                        {
                            Id = new Guid("60b82e02-14ee-431c-bb5a-2038b1483083"),
                            Emoji = "🎤 ",
                            Rating = 7.5999999999999996,
                            Title = "A Star is Born"
                        },
                        new
                        {
                            Id = new Guid("8d0e1c90-3dc7-464f-a9f6-1386d0712bc8"),
                            Emoji = "🧑‍🎤 ",
                            Rating = 7.9000000000000004,
                            Title = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = new Guid("33c70fae-89bb-4169-95e0-7f755c7d6625"),
                            Emoji = "🧑‍🎤 ",
                            Rating = 7.2999999999999998,
                            Title = "Rocketman"
                        },
                        new
                        {
                            Id = new Guid("f5525218-aac2-48cf-bbc7-d49b1b95272f"),
                            Emoji = "🧑‍🎤 ",
                            Rating = 7.2999999999999998,
                            Title = "Elvis"
                        },
                        new
                        {
                            Id = new Guid("4ab7230b-00cc-4c19-bf6c-10757b034069"),
                            Emoji = "🏆",
                            Rating = 8.0999999999999996,
                            Title = "Rush"
                        },
                        new
                        {
                            Id = new Guid("e3ae85e0-6863-41c9-ad60-6ab6809a0934"),
                            Emoji = "🏆",
                            Rating = 7.7000000000000002,
                            Title = "The Iron Claw"
                        },
                        new
                        {
                            Id = new Guid("f8743c4c-7237-4b09-bad7-23ef21f017e0"),
                            Emoji = "🏆",
                            Rating = 8.0999999999999996,
                            Title = "Ford v Ferrari"
                        },
                        new
                        {
                            Id = new Guid("3ece3ab6-7727-4bc0-9317-778c49f3015c"),
                            Emoji = "💌",
                            Rating = 7.7999999999999998,
                            Title = "Pride & Prejudice"
                        },
                        new
                        {
                            Id = new Guid("47f4cc72-559e-4278-bcc5-f703f289a0d5"),
                            Emoji = "💌",
                            Rating = 7.0,
                            Title = "Dirty Dancing"
                        },
                        new
                        {
                            Id = new Guid("cda4498c-7fda-4039-9d46-fa1cd83512a6"),
                            Emoji = "💌",
                            Rating = 7.7000000000000002,
                            Title = "Brokeback Mountain"
                        },
                        new
                        {
                            Id = new Guid("d34c3e25-41d7-4e71-8a84-8526ab524691"),
                            Emoji = "🩸",
                            Rating = 7.0999999999999996,
                            Title = "Late Night with the Devil"
                        },
                        new
                        {
                            Id = new Guid("aeb01cbc-0365-4773-801c-0e987329ef09"),
                            Emoji = "🩸",
                            Rating = 7.7999999999999998,
                            Title = "Get Out"
                        },
                        new
                        {
                            Id = new Guid("c09be204-ce54-4de2-aaaf-846b9ff3d3d2"),
                            Emoji = "🩸",
                            Rating = 6.7999999999999998,
                            Title = "The First Omen"
                        },
                        new
                        {
                            Id = new Guid("c16323d1-f1d5-4ba8-85a2-b6f2b425c511"),
                            Emoji = "😂",
                            Rating = 7.5999999999999996,
                            Title = "Superbad"
                        },
                        new
                        {
                            Id = new Guid("ee99387d-7c54-4eda-8ed6-94127ef9513a"),
                            Emoji = "😂",
                            Rating = 7.2999999999999998,
                            Title = "The Fall Guy"
                        },
                        new
                        {
                            Id = new Guid("cccf4cbb-9c69-424e-b52f-b234ba51c281"),
                            Emoji = "😂",
                            Rating = 7.9000000000000004,
                            Title = "The Holdovers"
                        },
                        new
                        {
                            Id = new Guid("191496d6-40cd-46ed-a749-4d6cc435d8ca"),
                            Emoji = "🔍",
                            Rating = 7.5999999999999996,
                            Title = "Killers of the Flower Moon"
                        },
                        new
                        {
                            Id = new Guid("d577bf06-829b-415b-816d-364367b90060"),
                            Emoji = "🔍",
                            Rating = 8.1999999999999993,
                            Title = "Shutter Island"
                        },
                        new
                        {
                            Id = new Guid("492e1cab-37a1-491f-b2e1-6b2c44272eb1"),
                            Emoji = "🔍",
                            Rating = 8.5,
                            Title = "The Prestige"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
